export const ACTION_TYPE = {
	// User actions
	SET_USER: 'SET_USER',
	UPDATE_USER: 'UPDATE_USER',
	LOGOUT: 'LOGOUT',

	//Project actions
	SET_PROJECTS: 'SET_PROJECTS',
	ADD_PROJECT: 'ADD_PROJECT',
	UPDATE_PROJECT: 'UPDATE_PROJECT',
	DELETE_PROJECT: 'DELETE_PROJECT',
	SET_CURRENT_PROJECT: 'ACTION_TYPE.SET_CURRENT_PROJECT:',

	// Time Entry actions
	SET_TIME_ENTRIES: 'SET_TIME_ENTRIES',
	ADD_TIME_ENTRY: 'ADD_TIME_ENTRY',
	UPDATE_TIME_ENTRY: 'UPDATE_TIME_ENTRY',
	DELETE_TIME_ENTRY: 'DELETE_TIME_ENTRY',
	START_TIMER: 'START_TIMER',
	STOP_TIMER: 'STOP_TIMER',
	SET_CURRENT_TIME_ENTRY: 'SET_CURRENT_TIME_ENTRY',

	//App action
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_LOADING: 'SET_LOADING', 
	SET_ERROR: 'SET_ERROR', 
};
